# The URL the site will be built for
base_url = "https://nttis.github.io/blog"

# Title and description used to generate feeds
title = "nttis' blog"
description = "Random ramblings"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Minify output HTML
minify_html = true

# Me!
author = "nttis"

# Generate feeds automatically
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

generate_sitemap = false
generate_robots_txt = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [{ theme = "gruvbox-light", filename = "syntax.css" }]

# Errors when a language is missing a syntax highlighter
error_on_missing_highlight = true

# Turn headings into anchors
insert_anchor_links = "heading"

# GitHub-style footnotes
bottom_footnotes = true

[extra]
# Put all your custom variables here
