on:
  push:
    branches:
      - "main"

name: Build and deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@c34a7626cd84c9c90499afeb310070ea838a8d1a
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
